
[mask]
url = "https://bit.ly/3TkYlGL"
autodownload_file = true

[gridT]
url_winter = "http://bit.ly/40ASWzZ"   # winter file
filename_winter = 'ANHA4-WLS001_y1980m01d05_gridT.nc'
url = "http://bit.ly/4frVeGa"  # summer file
filename = 'ANHA4-WLS001_y1980m07d14_gridT.nc'

[icebergs]
url = "http://bit.ly/3Z5vqKl"
filename = 'ANHA4-WLS001_y1980m01d05_icebergs.nc'
