
[mask]
url = "https://bit.ly/3TkYlGL"
autodownload_file = true

[gridT]
url = "http://bit.ly/40ASWzZ"
filename = 'ANHA4-WLS001_y1980m01d05_gridT.nc'

[icebergs]
url = "http://bit.ly/3Z5vqKl"
filename = 'ANHA4-WLS001_y1980m01d05_icebergs.nc'
